Monkey-patch resource loading function in GeckoLoader.
The function in GeckoLoader does not know about the file structure that
PyInstaller uses and was failing to locate the resource files for the
Gecko code handler, leading to obscure exceptions when the user
specified Gecko cheat codes in MKDD Extender:

```counterexample
Traceback (most recent call last):
  File "tools\GeckoLoader\GeckoLoader.py", line 223, in _exec
  File "pathlib.py", line 1013, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jane.doe\\Downloads\\mkdd-extender-2.10.1-windows-x64\\bin\\codehandler.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 4684, in _build
  File "gui.py", line 1878, in execute_and_wait
  File "gui.py", line 1836, in wrapped_func
  File "gui.py", line 4679, in <lambda>
  File "mkdd_extender.py", line 3795, in extend_game
  File "mkdd_extender.py", line 2905, in patch_dol_file
  File "mkdd_extender.py", line 2824, in inject_gecko_cheat_codes
  File "tools\GeckoLoader\GeckoLoader.py", line 246, in _exec
  File "tools\GeckoLoader\tools.py", line 68, in color_text
TypeError: can only concatenate str (not "FileNotFoundError") to str
```

Notice that, although a `FileNotFoundError` exception is originally
raised, there is a second exception as the wrong types are being
concatenated in GeckoLoader (programmer error), which made it extra
confusing.