Clear `LD_LIBRARY_PATH` before spawning system processes.
PyInstaller bundles copies of the libraries that the Python packages
depend on, and it sets `LD_LIBRARY_PATH` pointing to the internal
directory (`_internal`) that includes these libraries.

Most Linux systems have versions of these libraries too (DBus, etc.),
and the conflicting libraries provided by PyInstaller can make certain
system tools fail to launch (e.g. `xdg-open` or `dbus-send`).

For instance, when `xdg-open` was launched, the following messages could
be seen in the terminal:

```counterexample
xdg-mime: mimetype argument missing
Try 'xdg-mime --help' for more information.
Warning: unknown mime-type for ".../.config/mkdd-extender" -- using "application/octet-stream"
Error: no "view" mailcap rules found for type "application/octet-stream"
Opening ".../.config/mkdd-extender" with Caja  (inode/directory)
/usr/bin/caja: /tmp/.mount_mkdd-efyi65x/usr/bin/_internal/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libexempi.so.8)
/usr/bin/xdg-open: 882: x-www-browser: not found
Gtk-Message: 14:08:48.932: Failed to load module "xapp-gtk3-module"
```

The tool would still work but, instead of opening the system's file
browser, the default web browser would be launched, which was still
usable, but not ideal.

With `dbus-send`, the issue was more severe, as nothing would open up.
The following errors would be shown in the terminal:

```counterexample
dbus-send: /tmp/.mount_mkdd-eqIfRKD/usr/bin/_internal/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.14.10' not found (required by dbus-send)
Traceback (most recent call last):
  File "gui.py", line 3385, in <lambda>
  File "gui.py", line 328, in open_and_select_in_directory
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '('dbus-send', '--session', '--dest=org.freedesktop.FileManager1', '--type=method_call', '/org/freedesktop/FileManager1', 'org.freedesktop.FileManager1.ShowItems', 'array:string:file://.../Downloads/Courses/Reverse Luigi Circuit', 'string:""')' returned non-zero exit status 1
```

Although not verified, the issue would not affect Ubuntu 22.04, as that
is the version where the Linux build is compiled and the internal
libraries bundled by PyInstaller would likely match that version.