Ensure initial page number is set to at least 1.
When the value is not set (default), `None` was left in the variable,
which would cause an exception during the build:
```
Traceback (most recent call last):
  File "gui.py", line 3232, in _build
  File "gui.py", line 1131, in execute_and_wait
  File "gui.py", line 1097, in wrapped_func
  File "gui.py", line 3231, in <lambda>
  File "mkdd_extender.py", line 2380, in extend_game
  File "mkdd_extender.py", line 1949, in patch_dol_file
  File "code_patcher.py", line 1128, in patch_dol_file
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```