Add `rename()` helper function to handle special cases.
The function is mainly added to address an issue on Windows whereby
`os.rename()` can fail to move directories that have just been extracted
from an archive. An example of the traceback reported by Python:

```
Traceback (most recent call last):
  File "gui.py", line 2887, in _build
  File "gui.py", line 1121, in execute_and_wait
  File "gui.py", line 1087, in wrapped_func
  File "gui.py", line 2886, in <lambda>
  File "mkdd_extender.py", line 2383, in extend_game
  File "mkdd_extender.py", line 1569, in meld_courses
  File "mkdd_extender.py", line 469, in repack_course_arc_file
PermissionError: [WinError 5] Access is denied: 'C:\Users\alice\AppData\Local\Temp\mkddext_83yek7g\mario' -> 'C:\Users\alice\AppData\Local\Temp\mkddext_83yek7g\luigi2l'
```

It it thought that an antivirus can cause this error when quickly
grabbing the newly created directory just before the rename operation
is triggered.

The issue has been reported in other products too. For example:
- https://github.com/conan-io/conan/pull/6774
- https://github.com/conan-io/conan/pull/8915

The new `rename()` function will use **robocopy** (robust copy) if
available in the system (only Windows); no behavior change on other
platforms.

The helper function will now also check whether the destination exists,
instead of silently overridding potential files.